name: Run Visual Testing on Push

on:
  push:
    branches: main

env:
  NODE_VERSION: 20.x
  API_URL: ${{ secrets.API_URL }}
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY_DEVELOPMENT }}

jobs:
  visial-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: bahmutov/npm-install@v1

      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps

      - run: npm run test:visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
